# Generated by Django 3.0.5 on 2020-10-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
    ]
